services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=czyzlowie'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432'
  pgadmin:
    image: dpage/pgadmin4
    container_name: czyzlowie-pgadmin
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@admin.com'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    ports:
      - '5050:80'
    depends_on:
      - postgres