spring:
  application:
    name: czyzlowie

  datasource:
    url: jdbc:postgresql://localhost:5432/czyzlowie
    username: user
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
        format_sql: true
        highlight_sql: true
        generate_statistics: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  mail:
    host: localhost
    port: 1025

logging:
  level:
    pl.czyzlowie: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    liquibase: INFO

  docker:
    compose:
      lifecycle-management: start_and_stop
      startup:
        readiness:
          tcp:
            timeout: 10s
management:
  health:
    mail:
      enabled: false


imgw:
  api:
    meteo-url: https://danepubliczne.imgw.pl/api/data/meteo
    synop-url: https://danepubliczne.imgw.pl/api/data/synop
    hydro-url: https://danepubliczne.imgw.pl/api/data/hydro
  scheduler:
    # Meteo: 10 min
    meteo-rate: 600000
    # Hydro: 15 min
    hydro-rate: 900000
    # Synop: 30min
    synop-rate: 1800000
forecast:
  api:
    url: "https://api.open-meteo.com/v1/forecast"
